---
spring:
  profiles: first

server:
  port: 8886

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 20

      #hostname: eureka-first
  client:
      registerWithEureka: true #是否将eureka自身作为应用注册到eureka注册中心
      fetchRegistry: true #表示是否从eureka服务器获取注册信
      serviceUrl:
          defaultZone: http://192.168.1.7:8886/eureka/  #设置eureka服务器所在的地址，查询服务和注册服务都需要依赖这个地址
  #server:
      #enable-self-preservation: false #是否开启自我 保护(是否会清除已经下线的服务)

---
spring:
  profiles: secondly

server:
  port: 8887

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 20
    #hostname: eureka-secondly
  client:
      registerWithEureka: true #是否将eureka自身作为应用注册到eureka注册中心
      fetchRegistry: true #表示是否从eureka服务器获取注册信
      serviceUrl:
          defaultZone: http://192.168.254.55:8886/eureka/  #设置eureka服务器所在的地址，查询服务和注册服务都需要依赖这个地址
    #server:
      #enable-self-preservation: false #是否开启自我保护(是否会清除已经下线的服务)
